### ISSUE TITLE
access is denied

### ISSUE THREAD

**Issue by chiterl** [Polsu-Development/PolsuOverlay#14]
ion speak whatever this is
![etiogvjeovhe3ohefrt ovh](https://github.com/Polsu-Development/PolsuOverlay/assets/155512555/9686d78d-5220-4a64-8411-13e7e8cb4244)
but i js know it aint working

**Comment by Polsulpicien** [comment]
Hello chiterl, this logger.py file is to debug and troubleshoot errors like this one.
It seems that the overlay doesn't have perms to [create the new `logs` folder](https://github.com/Polsu-Development/PolsuOverlay/blob/main/src/components/logger.py#L51).  

There are two solutions, either you can:
- Create the folders manually with a folder named Polsu containing 4 folders 
![image](https://github.com/Polsu-Development/PolsuOverlay/assets/70817001/455b334e-ae45-432b-9b2f-225a13a05134)
- Run the overlay as administrator for the first time to enable the creation of those folders.

If you don't mind getting in contact with us via our [Discord server](https://discord.polsu.xyz) for further support.
Thank you and have a nice day.

**Comment by chiterl** [comment]
ok now that works and the overlay will actually work but i cant use it with lunar client???

**Comment by Polsulpicien** [comment]
Hi again, did you changed the client in the overlay settings to Lunar? You can access the settings by clicking the Polsu logo in the top left corner. Let me know if you need anything else!
![image](https://github.com/Polsu-Development/PolsuOverlay/assets/70817001/1756a46c-619a-4898-b33d-7fbe66baf643)

**Comment by chiterl** [comment]
that wasnt an option but i already fixed it, thx

**Comment by Polsulpicien** [comment]
If it wasn't an option this means the Overlay couldn't find lunar client installed. You are might not using the default installation path. In this case use the custom log path option 😄 
Glad it works now, let us know if you have other issues in the future!
