### ISSUE TITLE
add requeue level to the overlay

### ISSUE THREAD

**Issue by chiterl** [Polsu-Development/PolsuOverlay#23]
please js do 🙏

**Comment by raccoonmc** [comment]
but it's already there?

**Comment by Polsulpicien** [comment]
> but it's already there?

Yes it's already there...
![image](https://github.com/Polsu-Development/PolsuOverlay/assets/70817001/9ab5a4bb-c36d-493a-9195-03bb3d954c69)
It's the column before the ping :p
